SICRE/Controllers/CrediticioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SICRE.Models;

namespace SICRE.Controllers
{
	public class CrediticioController : Controller
	{
		private BDSICRE db = new BDSICRE();

		public ActionResult Index()
		{
			List<Crediticio> l = db.Crediticio.OrderByDescending(x => x.fechacreacion).Include(x => x.cliente).ToList();
			foreach (Crediticio o in l)
				o.lcalificacion = db.Calificacion.Where(x => x.idcrediticio == o.idcrediticio).Include(x => x.periodo).ToList();
			return View(l);
		}

		[HttpPost]
		public ActionResult Index(DateTime? fechacreacion = null, string ruc = "", string razon = "")
		{
			List<Crediticio> l = db.Crediticio.Where(
				x => (null == fechacreacion || x.fechacreacion == fechacreacion)
				&& ("" == ruc.Trim() || x.cliente.ruc.Contains(ruc.Trim()))
				&& ("" == razon.Trim() || x.cliente.nombre.Contains(razon.Trim())))
				.OrderByDescending(x => x.fechacreacion).Include(x => x.cliente).ToList();
			foreach (Crediticio o in l)
				o.lcalificacion = db.Calificacion.Where(x => x.idcrediticio == o.idcrediticio).Include(x => x.periodo).ToList();
			return View(l);
		}

		public ActionResult Details(int id = 0)
		{
			Crediticio crediticio = db.Crediticio.Include(x => x.cliente).SingleOrDefault(x => x.idcrediticio == id);
			crediticio.cliente_ruc = crediticio.cliente.ruc;
			crediticio.cliente_razon = crediticio.cliente.nombre;
			Session["lcalificacion"] = db.Calificacion.Where(x => x.idcrediticio == id).Include(x => x.periodo).ToList();
			if (crediticio == null)
				return HttpNotFound();
			return View(crediticio);
		}

		public ActionResult Create()
		{
			Crediticio crediticio = new Crediticio() { fechacreacion = DateTime.Now };
			Session["lcalificacion"] = new List<Calificacion>();
			return View(crediticio);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(Crediticio crediticio)
		{
			if (0 < db.Crediticio.Where(c => c.idpersona == crediticio.idpersona).Count())
				ModelState.AddModelError("cliente_ruc", "Ya existe un perfil para este cliente");
			if (0 == ((List<Calificacion>)Session["lcalificacion"]).Count())
				ModelState.AddModelError("idpersona", "Agregue una calificación");
			if (ModelState.IsValid)
			{
				db.Crediticio.Add(crediticio);
				db.SaveChanges();
				foreach (Calificacion o in ((List<Calificacion>)Session["lcalificacion"]))
				{
					db.Calificacion.Add(new Calificacion()
					{
						idcrediticio = crediticio.idcrediticio,
						idperiodo = o.idperiodo,
						deuda = o.deuda,
						entidad = o.entidad,
						normal = o.normal,
						problema = o.problema,
						deficiente = o.deficiente,
						dudoso = o.dudoso,
						perdida = o.perdida
					});
					db.SaveChanges();
				}
				return RedirectToAction("Index");
			}
			return View(crediticio);
		}

		public ActionResult Edit(int id = 0)
		{
			Crediticio crediticio = db.Crediticio.Include(x => x.cliente).SingleOrDefault(x => x.idcrediticio == id);
			crediticio.cliente_ruc = crediticio.cliente.ruc;
			crediticio.cliente_razon = crediticio.cliente.nombre;
			Session["lcalificacion"] = db.Calificacion.Where(x => x.idcrediticio == id).Include(x => x.periodo).ToList();
			if (crediticio == null)
				return HttpNotFound();
			return View(crediticio);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(Crediticio crediticio)
		{
			if (0 < db.Crediticio.Where(c => c.idpersona == crediticio.idpersona && c.idcrediticio != crediticio.idcrediticio).Count())
				ModelState.AddModelError("cliente_ruc", "Ya existe un perfil para este cliente");
			if (0 == ((List<Calificacion>)Session["lcalificacion"]).Count())
				ModelState.AddModelError("idpersona", "Agregue una calificación");
			if (ModelState.IsValid)
			{
				db.Entry(crediticio).State = EntityState.Modified;
				db.SaveChanges();
				List<Calificacion> lcalificacion = db.Calificacion.Where(x => x.idcrediticio == crediticio.idcrediticio).ToList();
				foreach (Calificacion calificacion in lcalificacion)
				{
					db.Calificacion.Remove(calificacion);
					db.SaveChanges();
				}
				foreach (Calificacion o in ((List<Calificacion>)Session["lcalificacion"]))
				{
					db.Calificacion.Add(new Calificacion()
					{
						idcrediticio = crediticio.idcrediticio,
						idperiodo = o.idperiodo,
						deuda = o.deuda,
						entidad = o.entidad,
						normal = o.normal,
						problema = o.problema,
						deficiente = o.deficiente,
						dudoso = o.dudoso,
						perdida = o.perdida
					});
					db.SaveChanges();
				}
				return RedirectToAction("Index");
			}
			return View(crediticio);
		}

		protected override void Dispose(bool disposing)
		{
			db.Dispose();
			base.Dispose(disposing);
		}

		public ActionResult IndexCalificacion()
		{
			return PartialView((List<Calificacion>)Session["lcalificacion"]);
		}

		public ActionResult IndexCalificacion2()
		{
			return PartialView((List<Calificacion>)Session["lcalificacion"]);
		}

		public ActionResult CreateCalificacion(int idcalificacion, int idcrediticio, int posicion)
		{
			Calificacion calificacion = posicion == 0 ? (new Calificacion() { idcalificacion = idcalificacion, idcrediticio = idcrediticio }) : ((List<Calificacion>)Session["lcalificacion"])[posicion - 1];
			ViewBag.idperiodo = new SelectList(db.Periodo, "idperiodo", "descripcion", calificacion.idperiodo);
			ViewBag.posicion = posicion.ToString();
			return PartialView(calificacion);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult CreateCalificacion(Calificacion calificacion, FormCollection collection)
		{
			ViewBag.posicion = collection["posicion"];
			int i = 0;
			if (calificacion.normal + calificacion.problema + calificacion.deficiente + calificacion.dudoso + calificacion.perdida != 100)
				ModelState.AddModelError("normal", "Ingrese correctamente los porcentajes");
			if (calificacion.deuda <= 0)
				ModelState.AddModelError("deuda", "Ingrese correctamente la deuda");
			if (calificacion.entidad <= 0)
				ModelState.AddModelError("entidad", "Ingrese correctamente el número de entidades");
			foreach (Calificacion o in (List<Calificacion>)Session["lcalificacion"])
			{
				i++;
				if (o.idperiodo == calificacion.idperiodo && i != int.Parse(collection["posicion"]))
				{
					ModelState.AddModelError("idperiodo", "Ya existe una calificación para este período");
					break;
				}
			}
			if (ModelState.IsValid)
			{
				ViewBag.OK = "1";
				calificacion.periodo = db.Periodo.Find(calificacion.idperiodo);
				if (collection["posicion"] == "0")
					((List<Calificacion>)Session["lcalificacion"]).Add(calificacion);
				else
					((List<Calificacion>)Session["lcalificacion"])[Convert.ToInt32(collection["posicion"]) - 1] = calificacion;
			}
			ViewBag.idperiodo = new SelectList(db.Periodo, "idperiodo", "descripcion", calificacion.idperiodo);
			return PartialView(calificacion);
		}
	}
}

SICRE/Controllers/SolicitudController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SICRE.Models;
using System.Data.Entity.Validation;
using System.Diagnostics;

namespace SICRE.Controllers
{
    public class SolicitudController : Controller
    {
        private BDSICRE db = new BDSICRE();

        public ActionResult Index()
		{
			ViewBag.idimportador = new SelectList(db.Cliente, "idpersona", "nombre");
			ViewBag.iddistribuidor = new SelectList(db.Cliente, "idpersona", "nombre");
			ViewBag.idaprobacion = new SelectList(db.Aprobacion, "idaprobacion", "descripcion");
			ViewBag.idhabilitacion = new SelectList(db.Habilitacion, "idhabilitacion", "descripcion");
			ViewBag.idmotivo = new SelectList(db.Motivo, "idmotivo", "descripcion");
            var solicitud = db.Solicitud.OrderByDescending(x => x.fechacreacion).Include(x => x.aprobacion).Include(x => x.importador).Include(x => x.distribuidor).Include(x => x.habilitacion).Include(x => x.motivo);
            return View(solicitud.ToList());
        }

		[HttpPost]
		public ActionResult Index(int idimportador = 0, int iddistribuidor = 0, int idaprobacion = 0, int idhabilitacion = 0, int idmotivo = 0, DateTime? fechacreacion = null)
		{
			ViewBag.idimportador = new SelectList(db.Cliente, "idpersona", "nombre", idimportador);
			ViewBag.iddistribuidor = new SelectList(db.Cliente, "idpersona", "nombre", iddistribuidor);
			ViewBag.idaprobacion = new SelectList(db.Aprobacion, "idaprobacion", "descripcion", idaprobacion);
			ViewBag.idhabilitacion = new SelectList(db.Habilitacion, "idhabilitacion", "descripcion", idhabilitacion);
			ViewBag.idmotivo = new SelectList(db.Motivo, "idmotivo", "descripcion", idmotivo);
			List<Solicitud> l = db.Solicitud.Where(
				x => (0 == idimportador || x.idimportador == idimportador)
				&& (0 == iddistribuidor || x.iddistribuidor == iddistribuidor)
				&& (0 == idaprobacion || x.idaprobacion == idaprobacion)
				&& (0 == idhabilitacion || x.idhabilitacion == idhabilitacion)
				&& (0 == idmotivo || x.idmotivo == idmotivo)
				&& (null == fechacreacion || x.fechacreacion == fechacreacion))
				.OrderByDescending(x => x.fechacreacion).Include(x => x.aprobacion).Include(x => x.importador).Include(x => x.distribuidor).Include(x => x.habilitacion).Include(x => x.motivo).ToList();
			return View(l);
		}

		public ActionResult IndexAnalista()
		{
			ViewBag.idanalista = new SelectList(db.Analista, "idpersona", "nombre");
			ViewBag.idanalistab = new SelectList(db.Analista, "idpersona", "nombre");
			var solicitud = db.Solicitud.OrderByDescending(x => x.fechacreacion).Include(x => x.importador).Include(x => x.distribuidor).Include(x => x.analista).Include(x => x.motivo);
			return View(solicitud.ToList());
		}

		[HttpPost]
		public ActionResult IndexAnalista(int[] idsolicitud, int idanalista = 0, int idanalistab = 0, int asignar = 0)
		{
			List<Solicitud> l = null;
			if (asignar == 1)
			{
				l = db.Solicitud.OrderByDescending(x => x.fechacreacion).Include(x => x.importador).Include(x => x.distribuidor).Include(x => x.analista).Include(x => x.motivo).ToList();
				if (idsolicitud != null && idsolicitud.Length > 0)
				{
					Solicitud solicitud = null;
					foreach (int i in idsolicitud)
					{
						solicitud = db.Solicitud.Find(i);
						solicitud.idanalista = idanalista;
						solicitud.importador_ruc = "x";
						solicitud.distribuidor_ruc = "x";
						solicitud.importador_razon = "x";
						solicitud.distribuidor_razon = "x";
						db.Entry(solicitud).State = EntityState.Modified;
						db.SaveChanges();
					}
				}
			}
			else
				l = db.Solicitud.Where(x => 0 == idanalistab || x.idanalista == idanalistab).OrderByDescending(x => x.fechacreacion).Include(x => x.importador).Include(x => x.distribuidor).Include(x => x.analista).Include(x => x.motivo).ToList();
			ViewBag.idanalista = new SelectList(db.Analista, "idpersona", "nombre", idanalista);
			ViewBag.idanalistab = new SelectList(db.Analista, "idpersona", "nombre", idanalistab);
			return View(l);
		}

		public ActionResult IndexDentro()
		{
			ViewBag.idimportador = new SelectList(db.Cliente, "idpersona", "nombre");
			ViewBag.iddistribuidor = new SelectList(db.Cliente, "idpersona", "nombre");
			ViewBag.idmotivo = new SelectList(db.Motivo, "idmotivo", "descripcion");
			var solicitud = db.Solicitud.OrderByDescending(x => x.fechacreacion).Include(x => x.importador).Include(x => x.distribuidor).Include(x => x.motivo);
			return View(solicitud.ToList());
		}

		[HttpPost]
		public ActionResult IndexDentro(int idimportador = 0, int iddistribuidor = 0, int idmotivo = 0)
		{
			ViewBag.idimportador = new SelectList(db.Cliente, "idpersona", "nombre", idimportador);
			ViewBag.iddistribuidor = new SelectList(db.Cliente, "idpersona", "nombre", iddistribuidor);
			ViewBag.idmotivo = new SelectList(db.Motivo, "idmotivo", "descripcion", idmotivo);
			var solicitud = db.Solicitud.Where(
				x => (0 == idimportador || x.idimportador == idimportador)
				&& (0 == iddistribuidor || x.iddistribuidor == iddistribuidor)
				&& (0 == idmotivo || x.idmotivo == idmotivo)).OrderByDescending(x => x.fechacreacion).Include(x => x.importador).Include(x => x.distribuidor).Include(x => x.motivo);
			return View(solicitud.ToList());
		}

		public ActionResult IndexSuperior()
		{
			ViewBag.idanalista = new SelectList(db.Analista, "idpersona", "nombre");
			ViewBag.idhabilitacion = new SelectList(db.Habilitacion.Where(x => x.idhabilitacion != 1), "idhabilitacion", "descripcion");
			var solicitud = db.Solicitud.Where(x => x.idhabilitacion != 1).OrderByDescending(x => x.fecharevision).Include(x => x.importador).Include(x => x.distribuidor).Include(x => x.analista).Include(x => x.habilitacion);
			return View(solicitud.ToList());
		}

		[HttpPost]
		public ActionResult IndexSuperior(int idanalista = 0, int idhabilitacion = 0, DateTime? fecharevision = null)
		{
			ViewBag.idanalista = new SelectList(db.Analista, "idpersona", "nombre", idanalista);
			ViewBag.idhabilitacion = new SelectList(db.Habilitacion.Where(x => x.idhabilitacion != 1), "idhabilitacion", "descripcion", idhabilitacion);
			var solicitud = db.Solicitud.Where(
				x => (0 == idanalista || x.idanalista == idanalista)
				&& (0 == idhabilitacion || x.idhabilitacion == idhabilitacion)
				&& (null == fecharevision || x.fecharevision == fecharevision)).OrderByDescending(x => x.fecharevision).Include(x => x.importador).Include(x => x.distribuidor).Include(x => x.analista).Include(x => x.habilitacion);
			return View(solicitud.ToList());
		}

        public ActionResult Details(int id = 0)
        {
			Solicitud solicitud = db.Solicitud.Include(x => x.importador).Include(x => x.distribuidor).SingleOrDefault(x => x.idsolicitud == id);
			solicitud.importador_ruc = solicitud.importador.ruc;
			solicitud.importador_razon = solicitud.importador.nombre;
			solicitud.distribuidor_ruc = solicitud.distribuidor.ruc;
			solicitud.distribuidor_razon = solicitud.distribuidor.nombre;
            if (solicitud == null)
                return HttpNotFound();
            ViewBag.idmotivo = new SelectList(db.Motivo, "idmotivo", "descripcion", solicitud.idmotivo);
            return View(solicitud);
        }

        public ActionResult Create()
        {
            ViewBag.idmotivo = new SelectList(db.Motivo, "idmotivo", "descripcion");
			Solicitud soliciud = new Solicitud() { idanalista = 1, idaprobacion = 1, idhabilitacion = 1, fechacreacion = DateTime.Now, aprobado = 0, garantizado = 0, garantia = false };
			return View(soliciud);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Solicitud solicitud)
        {
			if (solicitud.monto <= 0)
				ModelState.AddModelError("monto", "Ingrese correctamente el monto");
            if (ModelState.IsValid)
            {
				solicitud.idanalista = db.Analista.OrderBy(r => Guid.NewGuid()).Take(1).SingleOrDefault().idpersona;
                db.Solicitud.Add(solicitud);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idmotivo = new SelectList(db.Motivo, "idmotivo", "descripcion", solicitud.idmotivo);
            return View(solicitud);
		}

		public ActionResult CreateDentro(int id = 0)
		{
			Solicitud solicitud = db.Solicitud.Include(x => x.importador).Include(x => x.distribuidor).Include(x => x.motivo).SingleOrDefault(x => x.idsolicitud == id);
			solicitud.importador_ruc = "x";
			solicitud.distribuidor_ruc = "x";
			solicitud.importador_razon = "x";
			solicitud.distribuidor_razon = "x";
			ViewBag.idimportador = new SelectList(db.Cliente, "idpersona", "nombre", solicitud.idimportador);
			ViewBag.iddistribuidor = new SelectList(db.Cliente, "idpersona", "nombre", solicitud.iddistribuidor);
			ViewBag.idmotivo = new SelectList(db.Motivo, "idmotivo", "descripcion", solicitud.idmotivo);
			ViewBag.idaprobacion = new SelectList(db.Aprobacion, "idaprobacion", "descripcion", solicitud.idaprobacion);
			Session["lcalificacion"] = db.Calificacion.Where(x => x.idcrediticio == id).Include(x => x.periodo).OrderBy(x => x.periodo.descripcion).ToList();
			return View(solicitud);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult CreateDentro(Solicitud solicitud)
		{
			Analista analista = db.Analista.Find(solicitud.idanalista);
			if (solicitud.idaprobacion == 2 && solicitud.aprobado > analista.autonomia)
				ModelState.AddModelError("aprobado", "Monto aprobado supera autonomía. Solo puede grabar con dictamen recomendar aprobación");
			if (solicitud.idaprobacion == 3 && (solicitud.observacionaprobacion == null || solicitud.observacionaprobacion.Trim() == ""))
				ModelState.AddModelError("observacionaprobacion", "Es obligatorio ingresar una observación para el dictamen rechazar");
			if (solicitud.garantizado > solicitud.aprobado)

SICRE/Views/Solicitud/CreateDentro.cshtml
@model SICRE.Models.Solicitud

@{
	ViewBag.Title = "Asignar L.C. dentro de autonomía";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Asignar L.C. dentro de autonomía</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Solicitud</legend>

        @Html.HiddenFor(model => model.idsolicitud)
        @Html.HiddenFor(model => model.idimportador)
        @Html.HiddenFor(model => model.iddistribuidor)
        @Html.HiddenFor(model => model.idanalista)
        @Html.HiddenFor(model => model.idhabilitacion)
        @Html.HiddenFor(model => model.idmotivo)
        @Html.HiddenFor(model => model.monto)
        @Html.HiddenFor(model => model.fechacreacion)
        @Html.HiddenFor(model => model.fecharevision)
        @Html.HiddenFor(model => model.observacionhabilitacion)
        @Html.HiddenFor(model => model.importador_ruc)
        @Html.HiddenFor(model => model.distribuidor_ruc)
        @Html.HiddenFor(model => model.importador_razon)
        @Html.HiddenFor(model => model.distribuidor_razon)

		<div class="editor-label">
            @Html.LabelFor(model => model.idimportador)
        </div>
        <div class="editor-field">
            @Html.DropDownList("idimportador", null, "Seleccione importador", new { disabled = "disabled" })
        </div>

		<div class="editor-label">
            @Html.LabelFor(model => model.iddistribuidor)
        </div>
        <div class="editor-field">
            @Html.DropDownList("iddistribuidor", null, "Seleccione distribuidor", new { disabled = "disabled" })
        </div>

		<div class="editor-label">
            @Html.LabelFor(model => model.idmotivo)
        </div>
        <div class="editor-field">
            @Html.DropDownList("idmotivo", null, "Seleccione motivo", new { disabled = "disabled" })
        </div>

		<div class="editor-label">
            @Html.LabelFor(model => model.monto)
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.monto, new { @readonly = "readonly" })
        </div>

		<hr width="50%" align="left" />
		
        <div class="editor-label">
            @Html.Label("Seleccionar dictamen")
        </div>
        <div class="editor-field">
            @Html.DropDownList("idaprobacion", "Seleccione dictamen")
            @Html.ValidationMessageFor(model => model.idaprobacion)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.aprobado)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.aprobado)
            @Html.ValidationMessageFor(model => model.aprobado)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.garantia)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.garantia)
            @Html.ValidationMessageFor(model => model.garantia)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.garantizado)
        </div>
        <div class="editor-field">
			@if (Model.garantia) {
            @Html.TextBoxFor(model => model.garantizado)
			} else {
			@Html.TextBoxFor(model => model.garantizado, new { @readonly = "readonly" })
			}
            @Html.ValidationMessageFor(model => model.garantizado)
        </div>
		
        <div class="editor-label">
            @Html.Label("Observación")
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.observacionaprobacion)
            @Html.ValidationMessageFor(model => model.observacionaprobacion)
        </div>

        <p>
            <input type="submit" value="Grabar" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Cancelar", "IndexDentro")
</div>

<hr width="50%" align="left" />

<h2>Perfil crediticio</h2>

<div id="lcalificacion">@{ Html.RenderAction("IndexCalificacion2", "Crediticio"); }</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
<script type="text/jscript">
$(function () {
	$('#garantia').change(function () {
		if ($('#garantia').is(':checked')) {
			$('#garantizado').prop('readonly', false);
		} else {
			$('#garantizado').prop('readonly', true);
			$('#garantizado').val('0.00');
		}
	});
});
</script>
}

SICRE/Views/Solicitud/Index.cshtml
@model IEnumerable<SICRE.Models.Solicitud>

@{
    ViewBag.Title = "Solicitud de línea de crédito";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Solicitud de línea de crédito</h2>

<p>
    @Html.ActionLink("Agregar solicitud", "Create")
</p>

@using (Html.BeginForm("Index", "Solicitud", FormMethod.Post)) {
<fieldset>
    <legend>Búsqueda</legend>
	<table>
		<tr>
			<td><div class="editor-label">@Html.Label("Importador", new { @for = "idimportador" })</div></td>
			<td><div class="editor-field">@Html.DropDownList("idimportador", "Todos")</div></td>
			<td><input type="submit" value="Buscar" /></td>
		</tr>
		<tr>
			<td><div class="editor-label">@Html.Label("Distribuidor", new { @for = "iddistribuidor" })</div></td>
			<td><div class="editor-field">@Html.DropDownList("iddistribuidor", "Todos")</div></td>
			<td></td>
		</tr>
		<tr>
			<td><div class="editor-label">@Html.Label("Motivo", new { @for = "idmotivo" })</div></td>
			<td><div class="editor-field">@Html.DropDownList("idmotivo", "Todos")</div></td>
			<td></td>
		</tr>
		<tr>
			<td><div class="editor-label">@Html.Label("Estado de aprobación", new { @for = "idaprobacion" })</div></td>
			<td><div class="editor-field">@Html.DropDownList("idaprobacion", "Todos")</div></td>
			<td></td>
		</tr>
		<tr>
			<td><div class="editor-label">@Html.Label("Estado de habilitación", new { @for = "idhabilitacion" })</div></td>
			<td><div class="editor-field">@Html.DropDownList("idhabilitacion", "Todos")</div></td>
			<td></td>
		</tr>
		<tr>
			<td><div class="editor-label">@Html.Label("Fecha de creación", new { @for = "fechacreacion" })</div></td>
			<td><div class="editor-field">@Html.TextBox("fechacreacion")</div></td>
			<td></td>
		</tr>
	</table>
</fieldset>
}

@if (Model.Count() > 0) {

<table class="rvtabla">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.idimportador)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.iddistribuidor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.idmotivo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.monto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.idaprobacion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fecharevision)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.idhabilitacion)
        </th>
        <th>Opciones</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.importador.nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.distribuidor.nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.motivo.descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.monto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.aprobacion.descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.fecharevision)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.habilitacion.descripcion)
        </td>
        <td>
            @Html.ActionLink("Modificar", "Edit", new { id = item.idsolicitud }) |
            @Html.ActionLink("Consultar", "Details", new { id = item.idsolicitud })
        </td>
    </tr>
}

</table>
	
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
	@Scripts.Render("~/bundles/jqueryui")
<script type="text/javascript">
$(function () {
	$('#fechacreacion').datepicker({
		dateFormat: 'dd/mm/yy',
		changeMonth: true,
		changeYear: true
	});
});
</script>
}